### ISSUE TITLE
Update carbon dependency

### ISSUE THREAD

**Issue by sheriffmarley** [BadChoice/handesk-php#3]
Since laravel now uses nesbot/carbon 2 the installation of the package fails, since it requests version ~1.20 .

Possible to update it to the latest version?

**Comment by BadChoice** [comment]
sure!
Can you send me a PR so we can update it?

**Comment by holaa2019** [comment]
If I would know, how to do a pull request, I would. Just failed to install the handesk-php. Here are some truncated lines of error:
 Problem 1
    - Installation request for badchoice/handesk-php ^0.1.4 -> satisfiable by badchoice/handesk-php[0.1.4].
    - Conclusion: remove nesbot/carbon 2.24.0
    - Conclusion: don't install nesbot/carbon 2.24.0
    - badchoice/handesk-php 0.1.4 requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.20.0, 1.21.0,......1.39.0].
    - Can only install one of: nesbot/carbon[1.26.0, 2.24.0].
 ......
    - Can only install one of: nesbot/carbon[1.25.3, 2.24.0].
    - Installation request for nesbot/carbon (locked at 2.24.0) -> satisfiable by nesbot/carbon[2.24.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by ibennamdik** [comment]
i have this same issue

**Comment by BadChoice** [comment]
Done!
